name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      
      - name: Show Xcode Version
        run: |
          xcodebuild -version
          xcrun simctl list devices
          
      - name: Build
        run: |
          xcodebuild clean build \
            -project Octopus_Agile_Helper.xcodeproj \
            -scheme Octopus_Agile_Helper \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
      - name: Test
        run: |
          xcodebuild test \
            -project Octopus_Agile_Helper.xcodeproj \
            -scheme Octopus_Agile_Helper \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
