name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      
      - name: Show Environment
        run: |
          xcodebuild -version
          swift --version
          xcrun --sdk iphonesimulator --show-sdk-path
          echo "Available simulators:"
          xcrun simctl list devices
          
      - name: Verify Project Structure
        run: |
          echo "Project structure:"
          ls -R Octopus_Agile_Helper.xcodeproj
          echo "Project file contents:"
          plutil -p Octopus_Agile_Helper.xcodeproj/project.pbxproj
          
      - name: Build
        run: |
          xcodebuild clean build \
            -project Octopus_Agile_Helper.xcodeproj \
            -scheme Octopus_Agile_Helper \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -sdk iphonesimulator \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
          
      - name: Test
        run: |
          xcodebuild test \
            -project Octopus_Agile_Helper.xcodeproj \
            -scheme Octopus_Agile_Helper \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -sdk iphonesimulator \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
